[package]
name = "cite-me-bro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
biblatex = "0.9.3"
clap = { version = "4.5.4", features = ["derive", "unicode"] }
nom = "7.1.3"
nom-supreme = "0.8.0"
serde = { version = "1.0.202", features = ["derive"] }
