[tasks.doc-build]
command = "cargo"
args = ["doc", "--no-deps", "-q"]

[tasks.doc-post-proc]
command = "fd"
args = [
  ".",
  "./${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/doc/${CARGO_MAKE_CRATE_FS_NAME}",
  "-e",
  "html",
  "-x",
  "cmb",
  "-b",
  "cite.bib",
  "--style",
  "apa",
  "--format",
  "html",
  "-i",
  "{}",
]
dependencies = ["fd", "doc-build"]

[tasks.doc-http]
command = "http-server"
args = ['-i', '--cors', 'target/doc']

[tasks.doc-serve]
run_task = [{ name = ['doc-http', "doc-post-proc"], parallel = true }]

[tasks.fd]
install_crate = { crate_name = "fd-find", binary = "fd", test_arg = ["--help"] }

[tasks.http]
install_crate = { crate_name = "http-server", binary = "http-server", test_arg = [
  "--help",
] }
