name: Parsing Bug Report
description: Report a bug related to parsing .bib files
title: "[Parsing Bug] "
labels:
  - bug
  - parsing
body:
  - type: textarea
    attributes:
      label: description
      value: |
        ## Description

        <!-- Please describe the issue in detail. -->
  - type: textarea
    attributes:
      label: Minimum Working Example (MWE)
      description: "Provide a minimum working example of the .bib file that causes the issue."
      value: |
        ```bibtex
        <!-- .bib file content -->
        ```
  - type: textarea
    attributes:
      label: desired-behaviour
      value: |
        ## Desired Behavior

        <!-- Describe the behavior you expected. -->
